.Dd {{month}} {{day}}, {{year}}
.Dt {{document_title}} <%section%> <%arch_or_vol%>
.Os {{operating_system}} <%ver_or_release%>
.\"
.Sh NAME
.\" ====
.Nm {{name}}
.Nd {{name_description}}
.\"
.Sh SYNOPSIS
.\" ========
{{synopsis}}
.\"
.Sh DESCRIPTION
.\" ===========
{{description}}
.\"
.Sh SEE ALSO
.\" ========
{{#Xr document, section}}
