.Dd April 8, 2015
.Dt TIMELY 3 PRM  .\" Programmer's Manual \"
.Os libtimely 0.0.0
.\"
.\" @link <http://manpages.bsd.lv/mdoc.html>
.\"
.Sh NAME
.\" ====
.Nm libtimely
.Nd utilities to work with time values and structures
.\" This next command is for sections 2 and 3 only.
.\"
.Sh LIBRARY
.\" =======
.Lb timely
.\"
.Sh SYNOPSIS
.\" ========
.In timely.h
.\" ---
.Pp
.Fd #define ISO8601_UTC_SIZE 21
.\"
.Vt struct timely_moment ;
.\" ---
.Ft static inline int16_t
.Fn timely_day_of_year "uint16_t year, uint8_t month, uint8_t day"
.\" ---
.Ft static inline int8_t
.Fn timely_is_leap_year "uint16_t year"
.\" ---
.Ft static inline int
.Fn timely_iso8601_utc_timestamp "char *restrict dest, const time_t *restrict timer"
.\" ---
.Ft static inline int8_t
.Fn timely_num_days_in_month "uint16_t year, uint8_t month"
.\" ---
.Ft static inline int
.Fn timely_rfc1123_gmt_timestamp "char *restrict dest, const time_t *restrict timer"
.\" ---
.Ft static inline void
.Fn timely_set_default_locale "void"
.\" ---
.Ft struct tm *
.Fn timely_tm_ctor "struct tm *dest, const time_t *timer"
.\"
.Sh DESCRIPTION
.\" ===========
A helper lib for working with
.Dq Vt struct tm
structures and timestamps.
.\"
.Sh SEE ALSO
.\" ===========
.Xr timely_moment 3
